# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Для переобновления всех пакетов вводим
# pod deintegrate; pod install


target 'Open Weather UI Learn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Open Weather UI Learn
  pod 'Alamofire'
  pod 'SwiftKeychainWrapper'
  pod 'RealmSwift'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end
